########################################################################################
###                                     WALLPAPER                                    ###
########################################################################################

preload = ~/.config/hypr/wallpaper/1.png
preload = ~/.config/hypr/wallpaper/2.png
preload = ~/.config/hypr/wallpaper/3.png
preload = ~/.config/hypr/wallpaper/4.png
preload = ~/.config/hypr/wallpaper/5.png
preload = ~/.config/hypr/wallpaper/6.png
preload = ~/.config/hypr/wallpaper/7.png
preload = ~/.config/hypr/wallpaper/8.png

wallpaper {
    monitor = DP-1
    path = ~/.config/hypr/wallpaper/5.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = ~/.config/hypr/wallpaper/4.png
    fit_mode = cover
}



