return {
  {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
      preset = "helix",
      delay = 0,
      spec = {
        { "<leader>f", group = "find" },
        { "<leader>g", group = "git" },
        { "<leader>c", group = "code" },
        { "<leader>x", group = "diagnostics" },
        { "<leader>b", group = "buffer" },
        { "<leader>w", group = "windows" },
        { "<leader>t", group = "theme" },
        { "<leader>u", group = "ui" },
        { "<leader>q", group = "quit" },
        { "<leader>e", function() Snacks.explorer() end, desc = "File Explorer" },
        { "<leader>ff", function() Snacks.picker.files() end, desc = "Find File" },
        { "<leader>fr", function() Snacks.picker.recent() end, desc = "Recent Files" },
        { "<leader>fg", function() Snacks.picker.grep() end, desc = "Grep" },
        { "<leader>ca", vim.lsp.buf.code_action, desc = "Code Action" },
        { "<leader>cr", vim.lsp.buf.rename, desc = "Rename" },
        { "<leader>cd", vim.lsp.buf.definition, desc = "Go to Definition" },
        { "<leader>ch", vim.lsp.buf.hover, desc = "Hover Docs" },
        { "<leader>ci", vim.lsp.buf.implementation, desc = "Go to Implementation" },
        { "<leader>cf", function() require("conform").format() end, desc = "Format" },
        { "<leader>bd", ":bd<cr>", desc = "Delete Buffer" },
        { "<leader>bn", ":bnext<cr>", desc = "Next Buffer" },
        { "<leader>bp", ":bprev<cr>", desc = "Prev Buffer" },
        { "<leader>wv", "<C-w>v", desc = "Split Vertical" },
        { "<leader>wh", "<C-w>s", desc = "Split Horizontal" },
        { "<leader>wq", "<C-w>q", desc = "Close Window" },
        { "<leader>ww", "<C-w>w", desc = "Switch Window" },
        { "<leader>qq", ":qa<cr>", desc = "Quit All" },
        { "<leader>qw", ":wq<cr>", desc = "Save and Quit" },
        { "<leader>s", "<cmd>w<cr>", desc = "Save File" },
        { "<leader>un", function() Snacks.notifier.show_history() end, desc = "Notification History" },
        { "<leader>tt", ":Themery<cr>", desc = "Switch Theme" },
      },
    },
  },
}
